sonar.projectKey=erikaveloso_taskflow-devops
sonar.organization=erikaveloso

sonar.sources=backend/src,frontend/src

sonar.tests=backend/tests,frontend/src/tests

sonar.test.inclusions=**/*.spec.js,**/*.test.js,**/*.spec.jsx,**/*.test.jsx,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8